name: namer_app
description: "GoLorry / Laari Owner App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5

  # Utility
  english_words: ^4.0.0

  # Google Maps & Location
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0

  # Firebase (Backend)
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/laari.png
